name = "MultiresNet"
uuid = "e3025e60-cbac-441a-9b46-f5817c1c8a7b"
authors = ["Mateusz Kaduk <mateusz.kaduk@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
